---

  deployment_env: aia
  deployment_env_short: aia
  application_name: guardian-grrf

  aws_account: "156021229203"
  aws_region: us-east-1

  vpc_name: cts-{{ deployment_env }}-{{ application_name }}-vpc-01
  sg_name: cts-{{ deployment_env }}-{{ application_name }}-sg-01
  sg_cidr: "98.199.0.0/16"

  VpcId: vpc-04583eeaaac308059

  # reference:
  # https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
  eks_version: "1.18"
  eks_cluster_name: "cts-{{ deployment_env }}-{{ application_name}}-eks-cluster-01"
  eks_nodegroup_name: "cts-{{ deployment_env }}-{{ application_name }}-eks-ng-01"
  eks_instance_type: "t2.xlarge" # "c4.2xlarge" # m5a.xlarge
  eks_config_postfix: "-aia"

  # this gets overwriten by VPC creation
  eks_public_subnets: "subnet-0be071bf50ad2aee6,subnet-002d557e1b2c6db9b,subnet-0fa808293f99295db"
  eks_private_subnets: "subnet-01747a9730d177c4b,subnet-02bb448f61df34f9f,subnet-05ee6041a2513a6a6"
  subnets_used: "{{ eks_public_subnets }}"
  eks_type: eks
  eks_namespace: "guardian-embedded-analytics"

    # this is used in case load balancer for guardian-grrf app needs to be internal
  eks_elb_annotation: ""
  eks_alb_annotation: "alb.ingress.kubernetes.io/scheme: internet-facing"
  eks_alb_domain_name: "weather-services-aia.com"

  db_allocated_storage: 200
  db_instance_class: db.m4.xlarge
  db_instance_identifier: cts-{{ deployment_env }}-{{ application_name }}-rds-08
  db_name: "{{ deployment_env }}_{{ application_name }}_db"
  db_engine_version: "11.4"
  db_port: "5432"
  db_subnet_group_name: cts-{{ deployment_env }}-{{ application_name }}-sng-08 # this will be created
  db_is_public: "True"
  db_schema: guardian-grrf

  # this gets overwriten by VPC creation
  db_security_group: sg-0ed9ab22e849f52f6
  # this is overwriten during  02-postgres-create role execution
  db_endpoint: "{{ db_instance_identifier }}.cueeh1wa92dg.{{ aws_region }}.rds.amazonaws.com"

  ecr_private_repository: True
  ecr_repository_name: "cts-{{ deployment_env }}-{{ application_name }}"

  # this is overwriten during 04-repository-create role execution
  ecr_repository_uri: "{{ aws_account }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repository_name }}"

  # set the logging level for python apps
  # CRITICAL = 50
  # FATAL = CRITICAL
  # ERROR = 40
  # WARNING = 30
  # WARN = WARNING
  # INFO = 20
  # DEBUG = 10
  # NOTSET = 0
  WS_LOGLEVEL: INFO

  WX_STATION_SIZE_1h: 100
  WX_REPLICAS_1h: 4
  # WX_REPLICAS_1h: 13

  WX_STATION_SIZE_2d: 50
  WX_REPLICAS_2d: 7
  # WX_REPLICAS_2d: 26

  WX_STATION_SIZE_15d: 14
  WX_REPLICAS_15d: 26
  # WX_REPLICAS_15d: 90

  execute_vpc_create: 1
  execute_vpc_sg: 1
  execute_eks_create: 1
  execute_postgres_create: 1
  nodataload: 1
  execute_twistlock_scan: 0